### ISSUE TITLE
[FeatureRequest] val_score_key from losses

### ISSUE THREAD

**Issue by contentis** [delira-dev/delira#124]
**Description**
What should be added/changed?
When setting up the experiment it would be nice to have the possibility to use the criterions for the 'val_score_key'.

**Feature History**
What have you tried so far?

**Proposal**
How could the feature be implemented? 
*Are you able/willing to implement the feature yourself (with some guidance from us)?

**Additional context**
Add any other context about the feature request here.

**Comment by justusschock** [comment]
Unfortunately this is not that easily possible (and even if it would be, I don't know if I'd like to add it).

There are a (at least) 3 reasons for that:

**1.)** The `val_score_key` is used to select the best model during *validation*
**2.)** The criterions currently don't get calculated during validation (and I don't want them to be; See 3. for why not)
**3.)** The criterions work on the backend-specific tensor type (like `torch.Tensor`, `tf.Tensor`, `chainer.variable` etc.) to provide (automatic) differentiation capabilities and are not guaranteed to work on numpy arrays. To calculate them during validation, they would have to work on numpy.

Since metric/criterion calculation is usually really cheap (compared to the actual model forward- and backpropagation); If you know, your criterion is also working on numpy, I suggest you to simply add it to the metrics too.
