### ISSUE TITLE
Can pytorch_tensor_to_numpy backword gradient?

### ISSUE THREAD

**Issue by Guocode** [delira-dev/delira#40]
As torch op has rewrote it's own backward function, the step pytorch_tensor_to_numpy is out of torch op, can it backward gradient to former layers?

**Comment by justusschock** [comment]
Hi,

No it can't. For gradient taping (and automated differentiation), you have to stick with the functions provided by `torch` in it's namespace or define them yourself by giving an explicit backward.
Since numpy does not. Support gradients in the same way pytorch does, there is no way to propagate gradients through this function. Therefore this function is only for conversion.
