### ISSUE TITLE
[FeatureRequest] Dataset API expect more than one path for a sample 

### ISSUE THREAD

**Issue by gedoensmax** [delira-dev/delira#99]
**Description**
For data loading it is often important to have a ground truth path and a data path to pass to your loading function. At the moment it looks like this in `BaseCacheDataset` for example:
```
if isinstance(path, list):
            # iterate over all elements
            for p in tqdm(path, unit='samples', desc="Loading samples"):
data.append(self._load_fn(p, **self._load_kwargs))
```  
In Lazy Datasets this would be the same case for the __getitem__ method. 

**Proposal**
In my opininion we should add an asterisk in front of the p so that you could also pass lists of pathes to the load function. 
Personally i prefer using `**` in front of p and pass a list of dictionaries to the Dataset, as this would also allow passing some sort of label or whatever can be of interest for loading. But i am not sure what would be the more elegant way.

**Comment by justusschock** [comment]
You can do this by explicitly passing a (nested) list here and change your `load_fn` accordingly

EDIT: or you can just define your custom dataset by subclassing one of the existing datasets. These datasets are just base cases and I don't know if we want to support this as a default case, because this would make the default case more complicated, than it is just now. 

Thoughts @mibaumgartner @ORippler ?

**Comment by gedoensmax** [comment]
I know that i can pass a nested list there or nested dict list. I just thought i would make the BaseDatasets more capable without subclassing and make load functions more readable.

**Comment by mibaumgartner** [comment]
I prefer the current implementation becuase it does not assume any specific structure inside the list. The `*` operator would limit the items to tuple/list etc. , while `**` only works for dict like items. 

Furthermore, one special case, where the label and data files are inside the same subfolder, is already implemented in `LoadSampleLabel` in `delira.data_loading.load_utils`.

**Comment by justusschock** [comment]
I don't think this would improve the readability since this would probably overload the basecase with functionality, which is almost never used by the majority of the users and adds lot's of additional checks to be done. 

Another point if you add a `*` in front of the p here, and it isn't a list, but a string or a pathlike object (as currently expected), you'll either split the string into single characters and pass each of them as an own argument (which will most likely result in an OS Error at best or a silently passing but highly unwanted behavior at worst), or you'd cause an error directly. 

To make this working you would have to introduce additional typechecks, while the current implementation is really general (and the problem with typechecks is, that there is always a type you didn't check against and a developer complaining about that, because that exact type would be a great match for his implementation).
